name: Sync Google Drive

on:
  schedule:
    - cron: '*/5 * * * *'  # Kjør hvert 5. minutt
  workflow_dispatch:  # Tillater manuell kjøring

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download and save files
        run: |
          mkdir -p content
          # Prosjektstatus
          curl -L "https://drive.google.com/uc?export=download&id=1rYjTVcbx_yQVPAt_LrEuPdPpDWFz3PhE" -o content/prosjektstatus.md
          # Beskrivelse
          curl -L "https://drive.google.com/uc?export=download&id=1Xbe8MH4ISzX3TcyQfMJlyjhNdQTPhaGR" -o content/beskrivelse.md
          # Arbeidsliste
          curl -L "https://drive.google.com/uc?export=download&id=1zvUPM-cITgVyNWBc9GI_1Xgrf9-EKed2" -o content/arbeidsliste.md
          # Ressurser
          curl -L "https://drive.google.com/uc?export=download&id=1kgt2xCY_om0Tz99E_qPYMfHBFrQtjYLG" -o content/ressurser.md
          # Skilting
          curl -L "https://drive.google.com/uc?export=download&id=1Q9SYD2d4tZbGfLDB1wmli2re5aXySSNr" -o content/skilting_og_hensyn.md

      - name: Check file contents
        run: |
          echo "Checking file contents..."
          for file in content/*.md; do
            echo "=== $file ==="
            cat "$file"
            echo
          done

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add content/*.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatisk oppdatering fra Google Drive"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
