name: Sync Google Drive Files

on:
  schedule:
    - cron: '*/5 * * * *'  # Kjører hvert 5. minutt
  workflow_dispatch:  # Tillater manuell kjøring

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download files from Google Drive
        uses: pew-actions/google-drive-download@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          files: |
            1zvUPM-cITgVyNWBc9GI_1Xgrf9-EKed2:content/arbeidsliste.md
            1Xbe8MH4ISzX3TcyQfMJlyjhNdQTPhaGR:content/beskrivelse.md
            1rYjTVcbx_yQVPAt_LrEuPdPpDWFz3PhE:content/prosjektstatus.md
            1kgt2xCY_om0Tz99E_qPYMfHBFrQtjYLG:content/ressurser.md
            1Q9SYD2d4tZbGfLDB1wmli2re5aXySSNr:content/skilting_og_hensyn.md

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add content/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatisk oppdatering av filer fra Google Drive" && git push)
