name: Sync Google Drive

on:
  schedule:
    - cron: '*/5 * * * *'  # Kjør hvert 5. minutt
  workflow_dispatch:  # Tillater manuell kjøring

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Google Drive Files Sync
        uses: pew-actions/google-drive-download@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          files: |
            - id: "1rYjTVcbx_yQVPAt_LrEuPdPpDWFz3PhE"
              path: "content/prosjektstatus.md"
            - id: "1Xbe8MH4ISzX3TcyQfMJlyjhNdQTPhaGR"
              path: "content/beskrivelse.md"
            - id: "1zvUPM-cITgVyNWBc9GI_1Xgrf9-EKed2"
              path: "content/arbeidsliste.md"
            - id: "1kgt2xCY_om0Tz99E_qPYMfHBFrQtjYLG"
              path: "content/ressurser.md"
            - id: "1Q9SYD2d4tZbGfLDB1wmli2re5aXySSNr"
              path: "content/skilting_og_hensyn.md"

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add content/*.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatisk oppdatering fra Google Drive"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
