name: Sync Google Drive

on:
  schedule:
    - cron: '*/5 * * * *'  # Kjør hvert 5. minutt
  workflow_dispatch:  # Tillater manuell kjøring

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Google Drive Files Sync
        uses: wei/wget@v1
        with:
          args: -O content/prosjektstatus.md "https://drive.google.com/uc?export=download&id=1rYjTVcbx_yQVPAt_LrEuPdPpDWFz3PhE"

      - name: Download beskrivelse
        uses: wei/wget@v1
        with:
          args: -O content/beskrivelse.md "https://drive.google.com/uc?export=download&id=1Xbe8MH4ISzX3TcyQfMJlyjhNdQTPhaGR"

      - name: Download arbeidsliste
        uses: wei/wget@v1
        with:
          args: -O content/arbeidsliste.md "https://drive.google.com/uc?export=download&id=1zvUPM-cITgVyNWBc9GI_1Xgrf9-EKed2"

      - name: Download ressurser
        uses: wei/wget@v1
        with:
          args: -O content/ressurser.md "https://drive.google.com/uc?export=download&id=1kgt2xCY_om0Tz99E_qPYMfHBFrQtjYLG"

      - name: Download skilting
        uses: wei/wget@v1
        with:
          args: -O content/skilting_og_hensyn.md "https://drive.google.com/uc?export=download&id=1Q9SYD2d4tZbGfLDB1wmli2re5aXySSNr"

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add content/*.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatisk oppdatering fra Google Drive"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
